name: CMake compilation

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build CMake example
      # Choose the working directory
      working-directory: ${{github.workspace}}/cmake-example
      shell: bash
      # Execute the build. 1. Create a build directory. 2. Config cmake. 3. Build the project using cmake
      run: (mkdir build;cmake -B build -S .;cmake --build build;./build/CPTS_223_CMake_Example)
